TAO-809: Niet standaard thema's en types groeperen onder "Overig"
Amsterdam/iot-api pull request #53
Opened 2021-12-07 14:17 UTC by moagstar

Voor zowel thema's als types kan een burger een vrije tekst waarde invullen. Als we alle willekeurige waardes laten zien in de front end zullen we een wildgroei aan waardes hebben. Vooral voor de filter is dit vervelend.

Deze oplossing doet het groeperen in de backend. Het zou ook een optie kunnen zijn om metadata naar de front end te sturen over de verschillende types en themas en het groeperen in de front end. @janthijs en ik hebben deze optie besproken en zijn tot de conclusie gekomen dat de makkelijkste route voor nu is om in de backend te groeperen. Mocht er een requirement komen 
om de oorspronkelijke waarde toch te tonen in de front end kunnen we alsnog die kant op gaan, maar vooralsnog lijkt die requirement er niet te zijn.

2021-12-14 10:39 UTC, jklardie requested changes

2021-12-14 10:39 UTC, jklardie commented on api/src/iot/serializers.py
> +        return list(dict.fromkeys(themes).keys())
waarom doe je `dict.fromkeys(themes).keys()`?

Als het gaat om uniqueness dan zie ik liever `list(set(themes))`

2021-12-14 10:43 UTC, moagstar commented on api/src/iot/serializers.py
> +        return list(dict.fromkeys(themes).keys())
Bij `list(set(themes))` wordt de volgorde veranderd, ik had een commentaar geplaatst, maar ik zie dat hij een regel te hoog staat.

2021-12-16 12:24 UTC, jklardie approved these changes

2021-12-16 12:25 UTC, merged